/*
    Last Modified: 2025-07-07 06:05
    Author: Maxim
    Contact: https://www.maxim.pe.kr
    License: © 2025 Maxim. All Rights Reserved.
*/
const languages = {
    // 그룹: 언어 팩 - 모든 언어에 공통으로 적용되는 값
    _default: {
        'logo_text': 'CHUU',
        'rep_name': 'Hanna Kim',
        'email_address': 'chuu@chuu.kr',
        'email_href': 'mailto:chuu@chuu.kr',
        'address_text': '633 W 5th St, Los Angeles, CA 90071, USA',
        'cake_lettering_base_price': '$55+',
        'cake_photo_base_price': '$65+',
        'cake_3d_base_price': '$85+',
        'cookies_01_price_3pack': '$11',
        'cookies_01_price_6pack': '$20',
        'cookies_02_price_3pack': '$12.5',
        'cookies_02_price_6pack': '$23',
        'cookies_03_price_10pack': '$45',
        'cookies_03_price_20pack': '$85',
        'cookies_04_price_3pack': '$12.5',
        'cookies_04_price_6pack': '$23',
        'cookies_05_price_3pack': '$14',
        'cookies_05_price_6pack': '$26',
        'cookies_06_price_3pack': '$15.5',
        'cookies_06_price_6pack': '$29',
        'cookies_07_price_3pack': '$12.5',
        'cookies_07_price_6pack': '$23',
        'cookies_08_price_3pack': '$14',
        'cookies_08_price_6pack': '$26',
        'cookies_09_price_3pack': '$15.5',
        'cookies_09_price_6pack': '$29'
    },
    // 그룹: 언어 팩 - 영어
    'en': {
        'site_title': 'CHUU - Custom Cakes & Cookies',
        'meta_description': 'Discover special custom cakes and handmade cookies from CHUU that make every moment a sweet gift.',
        'meta_keywords': 'lettering cake, photo cake, 3d cake, handmade cookies, custom cake, anniversary cake, gift cookies, CHUU',
        'home_subtitle': 'Baking your sweet moments',
        'overview_title': 'With Love, CHUU',
        'overview_desc': 'We make all your days as special as an anniversary with our heartfelt cakes and cookies. CHUU presents a one-of-a-kind sweetness with fresh ingredients and creative designs.',
        'promotion_title': 'Promotion',
        'promotion_desc': 'Check out the special offer prepared by CHUU!',
        'promotion_01_title': 'Get a Random Cookie Box with Cake Purchase',
        'promotion_01_desc': 'Customers who purchase any whole cake will receive a random box of CHUU\'s popular handmade cookies as a gift.',
        'cakes_title': 'Custom Cakes',
        'cakes_desc': 'We have prepared three types of custom cakes for your special day.',
        'cakes_lettering_title': 'Lettering Cake',
        'cakes_lettering_desc': 'A cake that conveys your heart by drawing your desired message or simple picture on the cream.',
        'cakes_photo_title': 'Photo Cake',
        'cakes_photo_desc': 'We print your precious memories on the cake using edible ink.',
        'cakes_3d_title': '3D Cake',
        'cakes_3d_desc': 'An eye-catching 3D cake shaped like a character or object.',
        'cake_lettering_option_01': 'Flavor',
        'cake_lettering_option_01_options': 'Vanilla (Default)<br />Choco (+$3)<br />Carrot (+$4)',
        'cake_lettering_option_02': 'Cream',
        'cake_lettering_option_02_options': 'Fresh Cream (Default)<br />Cream Cheese (+$4)',
        'cake_lettering_option_03': 'Size',
        'cake_lettering_option_03_options': 'Lunchbox (Default)<br />6-inch (+$15)<br />8-inch (+$25)',
        'cake_lettering_option_04': 'Design',
        'cake_lettering_option_04_options': 'Simple Lettering (Default)<br />Add Drawing (+$10~)',
        'cake_photo_option_01': 'Flavor',
        'cake_photo_option_01_options': 'Vanilla (Default)<br />Choco (+$3)<br />Red Velvet (+$5)',
        'cake_photo_option_02': 'Cream',
        'cake_photo_option_02_options': 'Fresh Cream (Default)<br />Cream Cheese (+$4)',
        'cake_photo_option_03': 'Size',
        'cake_photo_option_03_options': 'Lunchbox (Default)<br />6-inch (+$15)<br />8-inch (+$25)',
        'cake_photo_option_04': 'Design',
        'cake_photo_option_04_options': 'Default Print (Default)<br />Edit/Crop (+$8)',
        'cake_3d_option_01': 'Flavor',
        'cake_3d_option_01_options': 'Vanilla (Default)<br />Choco (+$5)',
        'cake_3d_option_02': 'Cream',
        'cake_3d_option_02_options': 'Buttercream only',
        'cake_3d_option_03': 'Size',
        'cake_3d_option_03_options': '6-inch size only',
        'cake_3d_option_04': 'Design',
        'cake_3d_option_04_options': 'Simple Shape (Default)<br />Complex (+$30~)',
        'pricing_base_fee_label': 'Base Price From',
        'cookies_title': 'Handmade Cookies',
        'cookies_desc': 'CHUU\'s sweet cookie lineup, perfect for gifts or a delightful tea time.',
        'cookies_price_label_3pack': '3-Pack Box',
        'cookies_price_label_6pack': '6-Pack Box',
        'cookies_price_label_10pack': '10-Pack Box',
        'cookies_price_label_20pack': '20-Pack Box',
        'cookies_01_title': 'Chocolate Chip Cookies',
        'cookies_01_desc': 'The classic taste of cookies dotted with dark chocolate chips.',
        'cookies_02_title': 'Earl Grey Tea Cookies',
        'cookies_02_desc': 'A cookie with a deep flavor, made by grinding fragrant Earl Grey tea leaves.',
        'cookies_03_title': 'Cheddar Cheese Crackers',
        'cookies_03_desc': 'An addictive cheddar cheese cookie with an explosion of sweet and savory charm.',
        'cookies_04_title': 'Matcha White Chocolate Cookie',
        'cookies_04_desc': 'A cookie that offers a deep and rich flavor with the perfect harmony of bitter Jeju matcha and sweet white chocolate.',
        'cookies_05_title': 'Red Velvet Cream Cheese Cookie',
        'cookies_05_desc': 'A fantastic taste featuring a dense red velvet cookie filled with a soft cream cheese filling.',
        'cookies_06_title': 'Oreo S\'mores Cookie',
        'cookies_06_desc': 'Crispy Oreos, chewy marshmallows, and rich chocolate come together to evoke memories of a campfire.',
        'cookies_07_title': 'Lemon Delight Cookie',
        'cookies_07_desc': 'Refreshing lemon zest and a sweet glaze combine to bring a burst of freshness to your mouth.',
        'cookies_08_title': 'Peanut Butter Pretzel Cookie',
        'cookies_08_desc': 'Salty pretzel pieces are added to a savory peanut butter base, creating an irresistible sweet and salty combination.',
        'cookies_09_title': 'Injeolmi Soboro Cookie',
        'cookies_09_desc': 'A cookie targeting traditional tastes, with a dough full of savory Injeolmi (Korean rice cake) powder topped with crispy soboro.',
        'faq_cake_01_q': 'How many days in advance should I order a cake?',
        'faq_cake_01_a': 'All cakes are made to order, so we recommend booking at least 3 days in advance. For complex designs, please inquire with more time.',
        'faq_cake_02_q': 'How do I store the cake?',
        'faq_cake_02_a': 'Please refrigerate the cake upon receipt. It is best enjoyed within 1-2 days.',
        'faq_cookie_01_q': 'Is it possible to order cookies in bulk?',
        'faq_cookie_01_a': 'Yes, bulk orders for gifts or group presents are available. Please inquire at least a week in advance, and we will produce them according to the quantity.',
        'faq_cookie_02_q': 'Can I request custom cookie designs?',
        'faq_cookie_02_a': 'For bulk orders of 50 or more, simple custom designs are possible. Please contact us for a separate consultation.',
        'faq_cookie_03_q': 'How should I store the cookies?',
        'faq_cookie_03_a': 'Store in a cool, dry place away from direct sunlight. They are best consumed within 3-5 days. You can also freeze them for longer storage.',
        'faq_cookie_04_q': 'Are the cookies made on the same day?',
        'faq_cookie_04_a': 'Yes, all our cookies are baked fresh on the same day they are sold to ensure the best taste and quality.',
        'process_title': 'Custom Order Process',
        'process_desc': 'CHUU\'s cakes are ordered and produced through the following process.',
        'process_01_title': 'Inquiry via Email',
        'process_01_desc': 'Please contact us via email with your desired cake type and options.',
        'process_02_title': 'Design & Quote Confirmation',
        'process_02_desc': 'After reviewing your order, our manager will contact you to finalize the design and quote.',
        'process_03_title': 'Cake Production',
        'process_03_desc': 'We begin crafting your cake with care on the reserved date.',
        'process_04_title': 'Pickup or Delivery',
        'process_04_desc': 'You can pick up the finished cake at the store or have it delivered.',
        'media_title': 'Advertising Video',
        'media_desc': 'Meet CHUU\'s lovely moments on video!',
        'location_title': 'Location'
    },
    // 그룹: 언어 팩 - 한국어
    'ko': {
        'site_title': 'CHUU - 주문 제작 케이크 & 쿠키',
        'meta_description': '달콤한 순간을 선물하는 CHUU의 특별한 주문 제작 케이크와 수제 쿠키를 만나보세요. 모든 순간이 더욱 특별해집니다.',
        'meta_keywords': '레터링 케이크, 포토 케이크, 입체 케이크, 수제 쿠키, 주문 제작 케이크, 기념일 케이크, 답례품 쿠키, CHUU',
        'home_subtitle': '당신의 달콤한 순간을 만들어요',
        'overview_title': '사랑을 담아, CHUU',
        'overview_desc': '정성껏 만든 케이크와 쿠키로 당신의 모든 날을 기념일처럼 특별하게 만들어 드립니다. CHUU는 신선한 재료와 독창적인 디자인으로 세상에 단 하나뿐인 달콤함을 선물합니다.',
        'promotion_title': '프로모션',

        'promotion_desc': 'CHUU에서 준비한 특별한 혜택을 만나보세요!',
        'promotion_01_title': '케이크 구매 시 랜덤 쿠키 박스 증정',
        'promotion_01_desc': '모든 홀케이크를 구매하시는 고객님께 CHUU의 인기 수제 쿠키가 담긴 랜덤 박스를 선물로 드립니다.',
        'cakes_title': '주문 제작 케이크',
        'cakes_desc': '당신의 특별한 날을 위해, 세 가지 유형의 맞춤 케이크를 준비했습니다.',
        'cakes_lettering_title': '레터링 케이크',
        'cakes_lettering_desc': '크림 위에 원하는 문구나 간단한 그림을 직접 그려 넣어 마음을 전하는 케이크입니다.',
        'cakes_photo_title': '포토 케이크',
        'cakes_photo_desc': '소중한 추억이 담긴 사진을 식용 잉크로 인쇄하여 케이크 위에 그대로 재현합니다.',
        'cakes_3d_title': '입체 케이크',
        'cakes_3d_desc': '캐릭터나 사물의 모양을 그대로 본떠 만드는, 시선을 사로잡는 3D 디자인 케이크입니다.',
        'cake_lettering_option_01': '맛',
        'cake_lettering_option_01_options': '바닐라(기본)<br />초코(+$3)<br />당근(+$4)',
        'cake_lettering_option_02': '크림',
        'cake_lettering_option_02_options': '생크림(기본)<br />크림치즈(+$4)',
        'cake_lettering_option_03': '크기',
        'cake_lettering_option_03_options': '도시락(기본)<br />1호(+$15)<br />2호(+$25)',
        'cake_lettering_option_04': '디자인',
        'cake_lettering_option_04_options': '간단 레터링(기본)<br />그림 추가(+$10~)',
        'cake_photo_option_01': '맛',
        'cake_photo_option_01_options': '바닐라(기본)<br />초코(+$3)<br />레드벨벳(+$5)',
        'cake_photo_option_02': '크림',
        'cake_photo_option_02_options': '생크림(기본)<br />크림치즈(+$4)',
        'cake_photo_option_03': '크기',
        'cake_photo_option_03_options': '도시락(기본)<br />1호(+$15)<br />2호(+$25)',
        'cake_photo_option_04': '디자인',
        'cake_photo_option_04_options': '기본 인쇄(기본)<br />누끼/편집(+$8)',
        'cake_3d_option_01': '맛',
        'cake_3d_option_01_options': '바닐라(기본)<br />초코(+$5)',
        'cake_3d_option_02': '크림',
        'cake_3d_option_02_options': '버터크림 고정',
        'cake_3d_option_03': '크기',
        'cake_3d_option_03_options': '1호 사이즈 고정',
        'cake_3d_option_04': '디자인',
        'cake_3d_option_04_options': '단순 형태(기본)<br />복잡 형태(+$30~)',
        'pricing_base_fee_label': '기본 시작가',
        'cookies_title': '수제 쿠키',
        'cookies_desc': '선물용으로도, 티타임에도 안성맞춤인 CHUU의 달콤한 쿠키 라인업입니다.',
        'cookies_price_label_3pack': '3개입 상자',
        'cookies_price_label_6pack': '6개입 상자',
        'cookies_price_label_10pack': '10개입 상자',
        'cookies_price_label_20pack': '20개입 상자',
        'cookies_01_title': '초콜릿 칩 쿠키',
        'cookies_01_desc': '다크 초콜릿 칩이 콕콕 박힌 클래식한 맛의 정석입니다.',
        'cookies_02_title': '얼그레이 티 쿠키',
        'cookies_02_desc': '향긋한 얼그레이 찻잎을 갈아 넣어 풍미가 깊은 쿠키입니다.',
        'cookies_03_title': '황치즈 크래커',
        'cookies_03_desc': '단짠의 매력이 폭발하는 중독성 강한 체다치즈 쿠키입니다.',
        'cookies_04_title': '말차 화이트초코 쿠키',
        'cookies_04_desc': '쌉싸름한 제주 말차와 달콤한 화이트 초콜릿이 어우러져 깊고 진한 풍미를 선사하는 쿠키입니다.',
        'cookies_05_title': '레드벨벳 크림치즈 쿠키',
        'cookies_05_desc': '꾸덕한 레드벨벳 쿠키 속에 부드러운 크림치즈 필링을 가득 채워 환상적인 맛을 자랑합니다.',
        'cookies_06_title': '오레오 스모어 쿠키',
        'cookies_06_desc': '바삭한 오레오와 쫀득한 마시멜로, 진한 초콜릿이 만나 캠프파이어의 추억을 떠올리게 합니다.',
        'cookies_07_title': '레몬 딜라이트 쿠키',
        'cookies_07_desc': '상큼한 레몬 제스트와 달콤한 글레이즈가 어우러져 입안 가득 상쾌함을 선사합니다.',
        'cookies_08_title': '피넛버터 프레첼 쿠키',
        'cookies_08_desc': '고소한 피넛버터 베이스에 짭짤한 프레첼 조각이 더해져 멈출 수 없는 단짠의 조화를 이룹니다.',
        'cookies_09_title': '인절미 소보로 쿠키',
        'cookies_09_desc': '고소한 인절미 가루를 듬뿍 넣은 반죽 위에 바삭한 소보로를 올려 할매니얼 입맛을 저격합니다.',
        'faq_cake_01_q': '케이크 주문은 최소 며칠 전에 해야 하나요?',
        'faq_cake_01_a': '모든 케이크는 주문 제작으로, 최소 3일 전 예약을 권장합니다. 복잡한 디자인은 여유있게 문의해주세요.',
        'faq_cake_02_q': '케이크 보관은 어떻게 하나요?',
        'faq_cake_02_a': '수령 후에는 반드시 냉장 보관해주시고, 가급적 1~2일 내에 드시는 것이 가장 맛있습니다.',
        'faq_cookie_01_q': '쿠키 대량 주문도 가능한가요?',
        'faq_cookie_01_a': '네, 답례품이나 단체 선물을 위한 대량 주문 가능합니다. 최소 일주일 전 문의해주시면 수량에 맞춰 제작해 드립니다.',
        'faq_cookie_02_q': '쿠키도 주문 제작이 가능한가요?',
        'faq_cookie_02_a': '50개 이상 대량 주문 시, 간단한 맞춤 디자인이 가능합니다. 별도 문의 부탁드립니다.',
        'faq_cookie_03_q': '쿠키 보관 방법이 궁금해요.',
        'faq_cookie_03_a': '직사광선을 피해 서늘하고 건조한 곳에 보관해주세요. 3~5일 내에 드시는 것이 가장 좋으며, 냉동 보관하시면 더 오래 즐기실 수 있습니다.',
        'faq_cookie_04_q': '쿠키는 당일 생산되나요?',
        'faq_cookie_04_a': '네, 저희 모든 쿠키는 최상의 맛과 품질을 위해 판매 당일 아침에 직접 굽고 있습니다.',
        'process_title': '주문 제작 절차',
        'process_desc': 'CHUU의 케이크는 아래와 같은 과정으로 주문 및 제작이 진행됩니다.',
        'process_01_title': '이메일 문의',
        'process_01_desc': '원하는 케이크 종류와 옵션을 기재하여 이메일로 문의해주세요.',
        'process_02_title': '디자인 및 견적 확인',
        'process_02_desc': '주문서 확인 후, 담당자가 최종 디자인과 견적을 확정하여 안내해 드립니다.',
        'process_03_title': '케이크 제작',
        'process_03_desc': '예약된 날짜에 맞춰 정성스럽게 케이크 제작을 시작합니다.',
        'process_04_title': '픽업 또는 배송',
        'process_04_desc': '완성된 케이크는 매장에서 직접 픽업하시거나 배송받을 수 있습니다.',
        'media_title': '광고 영상',
        'media_desc': '츄의 사랑스러운 순간을 영상으로 만나보세요!',
        'location_title': '오시는 길'
    }
};
